### ISSUE TITLE
Additional test ROMs

### ISSUE THREAD

**Issue by ghost** [eightlittlebits/elbgb#1]
I'm not sure if you're aware, but there are more test ROMs available [here](https://github.com/Gekkio/mooneye-gb) along with their source code. They were very helpful for getting a more accurate TMA implementation.

If you're interested in the details of the TMA and how it works, I've documented it more thoroughly [here](https://github.com/adam-becker/beta/wiki/tma). There are more edge cases that exist (The mooneye-gb tests cover them also), but I never got around to figuring out how to implement them elegantly with emergent behavior.

**Comment by eightlittlebits** [comment]
Thanks for the links to the test roms and additional documentation. I have come across the mooneye tests before now but haven't worked on trying to make them pass as yet. Currently working on a framework to automate running of these tests to prevent regressions with fixing newer ones.

I'll check out your timer docs.

Thanks again.
